apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider
  labels:
    app: nacos-istio-provider
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v1
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v1
    spec:
      containers:
        - name: nacos-istio-provider
          image: leis17/nacos-istio-provider:v1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: http://nacos:8848
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider-v2
  labels:
    app: nacos-istio-provider-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v2
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v2
    spec:
      containers:
        - name: nacos-istio-provider
          image: leis17/nacos-istio-provider:v1.0
          imagePullPolicy: Always
          env:
            - name: console_output
              value: "hi,i'm provider v2 ！！！ "
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: http://nacos:8848
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider-v3
  labels:
    app: nacos-istio-provider-v3
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v3
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v3
    spec:
      containers:
        - name: nacos-istio-provider
          image: leis17/nacos-istio-provider:v1.0
          imagePullPolicy: Always
          env:
            - name: console_output
              value: "hi,i'm provider v3 ！！！ "
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
                value: http://nacos:8848
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: nacos-istio-provider
  labels:
    app: nacos-istio-provider
spec:
  type: NodePort
  selector:
    app: nacos-istio-provider
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30203

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-comsumer
  labels:
    app: nacos-istio-comsumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-comsumer
      version: v1
  template:
    metadata:
      labels:
        app: nacos-istio-comsumer
        version: v1
    spec:
      containers:
        - name: nacos-istio-comsumer
          image: leis17/nacos-istio-consumer:v1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: http://nacos:8848
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nacos-istio-comsumer
  labels:
    app: nacos-istio-comsumer
spec:
  type: ClusterIP
  selector:
    app: nacos-istio-comsumer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: nacos
spec:
  endpoints:
    - address: 10.10.13.48
      ports:
        http-8848: 8848
  hosts:
    - nacos
  location: MESH_EXTERNAL
  ports:
    - name: http-8848
      number: 8848
      protocol: TCP
  resolution: STATIC
