apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider
  labels:
    app: nacos-istio-provider
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v1
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v1
    spec:
      containers:
        - name: nacos-istio-provider
          image: registry.cn-shenzhen.aliyuncs.com/solarmesh/nacos-istio-provider:v2.0
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider-v2
  labels:
    app: nacos-istio-provider-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v2
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v2
    spec:
      containers:
        - name: nacos-istio-provider
          image: registry.cn-shenzhen.aliyuncs.com/solarmesh/nacos-istio-provider:v2.0
          imagePullPolicy: Always
          env:
            - name: console_output
              value: "hi,i'm provider v2 ！！！ "
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-provider-v3
  labels:
    app: nacos-istio-provider-v3
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-provider
      version: v3
  template:
    metadata:
      labels:
        app: nacos-istio-provider
        version: v3
    spec:
      containers:
        - name: nacos-istio-provider
          image: registry.cn-shenzhen.aliyuncs.com/solarmesh/nacos-istio-provider:v2.0
          imagePullPolicy: Always
          env:
            - name: console_output
              value: "hi,i'm provider v3 ！！！ "
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081

---

#apiVersion: v1
#kind: Service
#metadata:
#  name: nacos-istio-provider
#  labels:
#    app: nacos-istio-provider
#spec:
#  type: NodePort
#  selector:
#    app: nacos-istio-provider
#  ports:
#    - name: http
#      protocol: TCP
#      port: 8081
#      targetPort: 8081
 #     nodePort: 30203

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-istio-comsumer
  labels:
    app: nacos-istio-comsumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-istio-comsumer
      version: v1
  template:
    metadata:
      labels:
        app: nacos-istio-comsumer
        version: v1
    spec:
      containers:
        - name: nacos-istio-comsumer
          image: registry.cn-shenzhen.aliyuncs.com/solarmesh/nacos-istio-consumer:v2.0
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nacos-istio-comsumer
  labels:
    app: nacos-istio-comsumer
spec:
  type: NodePort
  selector:
    app: nacos-istio-comsumer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30204
