apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr
spec:
  host: nacos-istio-porvider.default.svc.cluster.local
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
    - labels:
        version: v3
      name: v3

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dr
spec:
  hosts:
    - nacos-istio-provider.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: nacos-istio-provider.default.svc.cluster.local
            subset: v2
          weight: 100
