apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr
spec:
  host: mesh-server.test.public.nacos
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
    - labels:
        version: v3
      name: v3
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dr
spec:
  hosts:
    - mesh-server.test.public.nacos
  http:
    - route:
        - destination:
            host: mesh-server.test.public.nacos
            subset: v1
          weight: 100
