
spring:
  application:
    name: mesh-server

  cloud:
    nacos:
      discovery:
        server-addr: nacos.external:8849
        metadata:
          version: v1
        group: test

server:
  port: 8081


console:
  output: "hi,i'm provider v1 ！！！ "

