
spring:
  application:
    name: mesh-server

  cloud:
    nacos:
      discovery:
        server-addr: 10.10.13.48:8848
        metadata:
          version: v1
        group: test

server:
  port: 8081


console:
  output: "hi,i'm provider v1 ！！！ "

