
spring:
  application:
    name: mesh-client

  cloud:
    nacos:
      discovery:
        server-addr: nacos.external:8849
        group: test
        metadata:
          version: v1

server:
  port: 8080

